name: Crowdin branch cleanup

on:
  delete:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    if: startsWith(github.event.ref || github.event.pull_request.head.ref, 'feature/') ||
      startsWith(github.event.ref || github.event.pull_request.head.ref, 'bugfix/') ||
      startsWith(github.event.ref || github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete Crowdin branch
        run: npx @crowdin/cli@latest branch delete "${{ github.event.ref || github.event.pull_request.head.ref }}" -T "${{ secrets.CROWDIN_PERSONAL_TOKEN }}" -i "${{ secrets.CROWDIN_PROJECT_ID }}"
        continue-on-error: true
